(Inicio as number, Fim as number) =>
let
    Inicio = List.Dates(Date.From(Date.AddDays(DateTime.LocalNow(), Inicio)), Fim, #duration(1, 0, 0, 0)),
    #"Convertido para Tabela" = Table.FromList(Inicio, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Date", type date}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Date", "Data"}}),
    #"Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Ano", each Date.Year([Data]), Int64.Type),
    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Semana do Ano Inserida" = Table.AddColumn(#"Nome do Mês Inserido", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
    #"Nome do Dia Inserido" = Table.AddColumn(#"Semana do Ano Inserida", "Nome do Dia", each Date.DayOfWeekName([Data]), type text),
    #"Texto em Maiúscula" = Table.TransformColumns(#"Nome do Dia Inserido",{{"Nome do Mês", Text.Upper, type text}, {"Nome do Dia", Text.Upper, type text}})
in
    #"Texto em Maiúscula"
    
    "[
            List.Dates=List.Dates, 
            Date.From=Date.From, 
            Date.AddDays=Date.AddDays, 
            DateTime.LocalNow=DateTime.LocalNow, 
            Table.FromList=Table.FromList, 
            Splitter.SplitByNothing=Splitter.SplitByNothing, 
            ExtraValues.Error=ExtraValues.Error, 
            Table.TransformColumnTypes=Table.TransformColumnTypes, 
            Table.RenameColumns=Table.RenameColumns, 
            Table.AddColumn=Table.AddColumn,
            Date.Year=Date.Year, 
            Int64.Type=Int64.Type, 
            Date.Month=Date.Month, 
            Date.MonthName=Date.MonthName,
            Date.WeekOfYear=Date.WeekOfYear, 
            Date.DayOfWeekName=Date.DayOfWeekName, 
            Table.TransformColumns=Table.TransformColumns, 
            Text.Upper=Text.Upper
        ]"
