let
    Inicio = List.Dates(Date.From(Date.AddDays(DateTime.LocalNow(), 365)), 730, #duration(1, 0, 0, 0)),
    #"Convertido para Tabela" = Table.FromList(Inicio, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Convertido para Tabela",{{"Date", type date}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Date", "Data"}}),
    #"Ano Inserido" = Table.AddColumn(#"Colunas Renomeadas", "Ano", each Date.Year([Data]), Int64.Type),
    #"Mês Inserido" = Table.AddColumn(#"Ano Inserido", "Mês", each Date.Month([Data]), Int64.Type),
    #"Nome do Mês Inserido" = Table.AddColumn(#"Mês Inserido", "Nome do Mês", each Date.MonthName([Data]), type text),
    #"Semana do Ano Inserida" = Table.AddColumn(#"Nome do Mês Inserido", "Semana do Ano", each Date.WeekOfYear([Data]), Int64.Type),
    #"Nome do Dia Inserido" = Table.AddColumn(#"Semana do Ano Inserida", "Nome do Dia", each Date.DayOfWeekName([Data]), type text),
    #"Texto em Maiúscula" = Table.TransformColumns(#"Nome do Dia Inserido",{{"Nome do Mês", Text.Upper, type text}, {"Nome do Dia", Text.Upper, type text}})
in
    #"Texto em Maiúscula"
